spring:
  application:
    name: hohofast
  resources:
    static-locations: classpath:/
  datasource:
    # 测试
    username: xxx
    password: xxxx
    url: jdbc:mysql://xxxx:3306/hohofast_test5?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
#    #HikariDataSource
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 10
#      idle-timeout: 600000
#      auto-commit: true
#      pool-name: MyHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml