server:
  port: 8090
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: admin
    password: 123456
    platform: h2
    data: classpath:/db/data.sql
    schema: classpath:/db/schema.sql


mybatis:
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
