server:
  port: 8101
#====================================stream =============================================
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${base-server.mysql.addr}/seata?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: ${base-server.mysql.username}
    password: ${base-server.mysql.password}
  application:
    name: dubbo-storage-example

#====================================Dubbo config===============================================
dubbo:
  application:
    id: dubbo-order-example
    name: dubbo-order-example
    qosEnable: false
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    id: dubbo-storage-example-registry
    address: nacos://${base-server.nacos-addr}
  config-center:
    address: nacos://${base-server.nacos-addr}
  metadata-report:
    address: nacos://${base-server.nacos-addr}
#====================================mybatis-plus config===============================================
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: io.seata.samples.integration.*.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

#====================================Seata Config===============================================
seata:
  enabled: true
  application-id: order-seata-example
  tx-service-group: order-service-seata-service-group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  client:
    rm-report-success-enable: true
    rm-table-meta-check-enable: false # 自动刷新缓存中的表结构（默认false）
    rm-report-retry-count: 5 # 一阶段结果上报TC重试次数（默认5）
    rm-async-commit-buffer-limit: 10000 # 异步提交缓存队列长度（默认10000）
    rm:
      lock:
        lock-retry-times:    30 # 校验或占用全局锁重试次数（默认30）
        lock-retry-policy-branch-rollback-on-conflict: true # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
        lock-retry-interval: 10 # 校验或占用全局锁重试间隔（默认10ms）
    tm-commit-retry-count:   3 # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
    tm-rollback-retry-count: 3 # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
    undo:
      undo-data-validation: true # 二阶段回滚镜像校验（默认true开启）
      undo-log-serialization: jackson # undo序列化方式（默认jackson）
      undo-log-table: undo_log  # 自定义undo表名（默认undo_log）
    log:
      exceptionRate: 100 # 日志异常输出概率（默认100）
    support:
      spring:
        datasource-autoproxy: true
  service:
    vgroup-mapping: default # TC 集群（必须与seata-server保持一致）
    enable-degrade: false # 降级开关
    disable-global-transaction: false # 禁用全局事务（默认false）
    grouplist: ${base-server.seata-addr}
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true # 客户端事务消息请求是否批量合并发送（默认true）
  registry:
    file:
      name: file.conf
    type: nacos
    nacos:
      server-addr: ${base-server.nacos-addr}
      namespace: "0842cd23-b1ca-48f2-abca-67225d35248b"
      cluster: default
  config:
    file:
      name: file.conf
    type: nacos
    nacos:
      namespace: "0842cd23-b1ca-48f2-abca-67225d35248b"
      server-addr: ${base-server.nacos-addr}

base-server:
  nacos-addr: 127.0.0.1:8848
  seata-addr: 127.0.0.1:8091
  mysql:
    addr: 127.0.0.1:3306
    username: root
    password: Admin123
